name: Docker Image CI

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login ghcr.io -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the base Docker
      working-directory: ./dockerfiles/tfe22-2_gruppe7_image
      run: docker build . --file Dockerfile --tag ghcr.io/tonist52/tfe22-2_gruppe7_image
    - name: docker push base
      run: docker push ghcr.io/tonist52/tfe22-2_gruppe7_image